#-------------------------------
# General Site Settings

title: Yash Mahajan
logo: 
email: yashmahajan@vt.edu
phone: +540 998 8188
address: 236 Pheasant Run Drive, Blacksburg, VA

menu:
- {name: About, link: '/about/'}
- {name: Research, link: '/blog/'}
- {name: Publication and Resume, link: '/portfolio/'}
- {name: Contact, link: '/contact/'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Yash Mahajan 

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/yash-mahajan-19486a126/"}
- {icon: "ti-github", link: "https://github.com/yashmahajan10"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  My name is Yash Mahajan and I am pursuing Master of Science in Computer Science and Application from Virginia Polytechnic and State University (Virginia Tech). I completed my Bachelor of Technology in Computer Science with specialisation in Bioinformatics from Vellore Insititue of Technology (VIT) in the year 2019 and I felt that I needed some real research experience to know the nuances in the field of Social Network Analysis, which is where my research interest lies.   

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Research and Planning focusses the researcher so that before they begin their research, they fully understand what the research objectives are and what actions they need to take to achieve that objective."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Defining the components, modules, interfaces, and data for a system to satisfy and achieve the research objectives. Putting the thoughts into actions. "
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Coming up with a tangible or intangible product which satisifes the deliverables and succesfully tackles the research objective.  "




#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Back-end Development, color: '#9473e6', value: '90%'}
- {name: Front-end Development, color: '#fdb157', value: '80%'}
- {name: Machine Learning, color: '#bdecf6', value: '70%'}
- {name: Blockchain, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Full-Stack Intern, icon: 'icon-1.png', date: 'Dec 2016 - Jan 2017', organization: 'The Glitch Pvt Media Ltd'}
- {name: Back-end Intern, icon: 'icon-2.png', date: 'May 2018 - Aug 2018', organization: 'Reliance Infocomm Ltd'}
- {name: Co-op, icon: 'icon-3.png', date: 'Dec 2018 - May 2019', organization: 'Reliance Industries Ltd'}
- {name: Graduate Teaching Assisant, icon: 'icon-1.png', date: 'Dec 2019 - Present', organization: 'Virginia Tech'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Master of Science in Computer Science and Application, date: '2019 - Present', organization: 'Virginia Polytechnic Institute and State University (Virginia Tech)'}
- {name: Bachelor of Technology in Computer Science, date: '2015-2019', organization: 'Vellore Institute of Technology (VIT)'}
- {name: Higher Secondary Certificate, date: '2015', organization: 'Hiranandani Foundation School'}
- {name: Secondary School Certificate, date: '2013', organization: 'Hiranandani Foundation School'}



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Dilip Krishnaswamy"
    image: "assets/images/user-3.jpg"
    designation : "Vice President, Reliance Industries Ltd."
    content : "During his intership and co-op, Yash showed great enthusiasm to learn new areas and concepts. He has the ability to learn quickly, and he was extremely diligent in his work. He was also very keen to produce work of high quality when he worked
on the MNP Blockchain project. Yash has very good ability to work independently as well as in a team."
    


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: yashmahajan@vt.edu